### ISSUE TITLE
Question about jsx attributes

### ISSUE THREAD

**Issue by inside** [whatyouhide/vim-textobj-xmlattr#5]
Hi,

I use this plugin everyday for html editing and also more and more jsx. Do you think it would make sense to add jsx attributes support?

As mentionned is [this vim reddit thread](https://www.reddit.com/r/vim/comments/4m6o2g/using_vim_for_web_developent_htmlcssjavascript/d3t6tw5), it doesn't work all the time with jsx attributes.

Best,

**Comment by whatyouhide** [comment]
@inside I don't write JSX at all sadly so I'm kind of out of touch with that 😕 That said, I would say that if JSX is not valid XML, then we can probably just have another package (vim-textobj-jsxattr for example) that handles that (you could copy and adjust the code in this repo directly). I would do this so that this plugin stays focused and well-scoped :) Wdyt?

**Comment by inside** [comment]
I like the idea of another package to stay focused and well-scope. The challenge would be to have the same mapping whether you are editing xml/html or jsx. I'll have a closer look at vim-textobj-user, I think about explicitly creating mappings in the vimrc for specific filetypes.

Thanks for your plugin and reply :-)

**Comment by whatyouhide** [comment]
Sounds like a good starting point. Sorry I won't be part of that, but I again don't write any JSX at all and also, don't use vim anymore so it's kind of hard for me to get into that 😄

**Comment by inside** [comment]
It's ok! I'll let you know when I have something ready.
Out of curiosity, what's your new editor?

Best,

**Comment by whatyouhide** [comment]
@inside there's only one other editor capable of challenging vim, Emacs of course :)

**Comment by inside** [comment]
Hahaha!! This thread is mutating into a troll ;-)
I don't know Emacs very well, bu I guess if you use evil-mode, you got the best of both worlds.

Have a nice journey with Emacs!!
