### ISSUE TITLE
The line with the only attribute is not deleted

### ISSUE THREAD

**Issue by MeShootIn** [whatyouhide/vim-textobj-xmlattr#8]
Suppose we have the tag from the example in _README.md_, but the attributes are separated by line breaks (sometimes linters do this when the allowed line length is exceeded):
```xml
<div
  class="box"
  id=footer
  data-updatable
  data-content="everything"
></div>
```
After the `dax` operation on any attribute (for example, let it be on the first one), an empty string remains:
```xml
<div
  
  id=footer
  data-updatable
  data-content="everything"
></div>
```
It seems to me that the separator in the form of a line break, as well as in the form of a whitespace, should also be removed.

**Comment by whatyouhide** [comment]
Hey, I haven't used vim in years, sorry! This is not maintained anymore effectively. If you want, feel free to contribute the fix to this and I'll be happy to review and merge 🙃
